const SB_URL='https://obiekxxujgvlcjqvdsji.supabase.co';
const SB_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYXNlIiwicmVmIjoib2JpZWt4eHVqZ3ZsY2pxdmRzamkiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc4MTE2NzY0OSwiZXhwIjoyMDk2NzQzNjQ5fQ.EOI6QTMfvE3PrAXyL_PIYVes5_OPBAC2K5gseiNRnQ0';
const sb=window.supabase.createClient(SB_URL,SB_KEY);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let user=null, year=2026, clients=[], responsaveis=[], currentPage='resumo', dirtyServices=new Map();

const groups=[
 ['Base',[['clientes','Clientes'],['servicos','Gestão de Serviços'],['responsaveis','Responsáveis']]],
 ['Fiscal',[['iva-cessado','IVA Cessado'],['iva-mensal','IVA Mensal'],['iva-trimestral','IVA Trimestral'],['saft','SAFT'],['retencoes','Retenções'],['modelo30','Modelo 30'],['independentes','Independentes'],['fecho-anual','Fecho Anual']]],
 ['Laboral / Estatístico',[['salarios','Salários & DMR'],['cope','COPE & INE']]],
 ['Gestão',[['resumo','Resumo'],['calendario','Calendário Fiscal'],['auditoria','Auditoria']]]
];

const serviceFlags={cope:'tem_cope','iva-trimestral':'tem_iva_trimestral','iva-mensal':'tem_iva_mensal',saft:'tem_saft',salarios:'tem_salarios',retencoes:'tem_retencoes','fecho-anual':'tem_fecho_anual',modelo30:'tem_modelo30',independentes:'tem_independente'};

const moduleConfig={
 'iva-mensal':{title:'IVA Mensal',periods:[...Array(12)].map((_,i)=>String(i+1)),flag:'tem_iva_mensal',fields:[
  ['entrada','Entrada','date'],['bancos','Bancos','date'],['arquivo','Arquivo','date'],['int_vendas','Int. Vendas','date'],['lancamento','Lançamento IVA','date'],['resp_execucao','Resp. Exec.','user'],['docs_em_falta','Docs falta','text'],['saldo_iva','Saldo IVA','money'],['pedir_plano','Pedir plano','bool-negative'],['reembolso','Reembolso','bool-positive'],['plano_executado','Plano exec.','date-negative'],['estado','Estado','status'],['envio','Envio','date'],['obs','Obs.','text'] ]},
 'iva-trimestral':{title:'IVA Trimestral',periods:['1','2','3','4'],flag:'tem_iva_trimestral',fields:[
  ['bancos_m1','Bancos M1','date'],['bancos_m2','Bancos M2','date'],['bancos_m3','Bancos M3','date'],['lancamento','Lançamento IVA','date'],['resp_execucao','Resp. Exec.','user'],['docs_em_falta','Docs falta','text'],['saldo_iva','Saldo IVA','money'],['pedir_plano','Pedir plano','bool-negative'],['reembolso','Reembolso','bool-positive'],['plano_executado','Plano exec.','date-negative'],['estado','Estado','status'],['envio','Envio','date'],['obs','Obs.','text'] ]},
 saft:{title:'SAFT',periods:['ano'],flag:'tem_saft',fields:[['resp_execucao','Resp. Exec.','user'],['estado','Estado','status'],['envio','Envio','date'],['obs','Obs.','text']]},
 retencoes:{title:'Retenções',periods:[...Array(12)].map((_,i)=>String(i+1)),flag:'tem_retencoes',fields:[['valor','Valor','money'],['resp_execucao','Resp. Exec.','user'],['estado','Estado','status'],['envio','Envio','date'],['obs','Obs.','text']]},
 modelo30:{title:'Modelo 30',periods:[...Array(12)].map((_,i)=>String(i+1)),flag:'tem_modelo30',fields:[['valor','Valor','money'],['resp_execucao','Resp. Exec.','user'],['estado','Estado','status'],['envio','Envio','date'],['obs','Obs.','text']]},
 salarios:{title:'Salários & DMR',periods:[...Array(12)].map((_,i)=>String(i+1)),flag:'tem_salarios',fields:[['processamento','Processamento','date'],['dmr','DMR','date'],['resp_execucao','Resp. Exec.','user'],['estado','Estado','status'],['obs','Obs.','text']]},
 cope:{title:'COPE & INE',periods:[...Array(12)].map((_,i)=>String(i+1)),flag:'tem_cope',fields:[['estado','Estado','status'],['obs','Obs.','text']]},
 independentes:{title:'Independentes',periods:['1','2','3','4'],flag:'tem_independente',fields:[['resp_execucao','Resp. Exec.','user'],['estado','Estado','status'],['envio','Envio','date'],['obs','Obs.','text']]},
 'fecho-anual':{title:'Fecho Anual',periods:['ano'],flag:'tem_fecho_anual',fields:[['resp_execucao','Resp. Exec.','user'],['estado','Estado','status'],['data_fecho','Data de fecho','date'],['obs','Observações','text']]}
};

function toast(msg,type='ok'){const d=document.createElement('div');d.className='toast '+type;d.textContent=msg;$('#toast').append(d);setTimeout(()=>d.remove(),3500)}
function normRole(v=''){v=v.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').trim();return v.includes('admin')?'administrador':v.includes('tec')?'tecnico':'operacional'}
function isAdmin(){return normRole(user?.nivel)==='administrador'}
function canManage(){return ['administrador','tecnico'].includes(normRole(user?.nivel))}
function fmtDate(v){return v?new Date(v+'T00:00:00').toLocaleDateString('pt-PT'):''}
function monthName(m){return ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'][Number(m)-1]||m}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

async function boot(){
 const [ru,rc]=await Promise.all([sb.from('responsaveis').select('*').eq('estado','Ativo').order('nome'),sb.from('clientes').select('*').order('codigo')]);
 if(ru.error||rc.error){$('#login-error').textContent='Erro de ligação ao Supabase';return}
 responsaveis=ru.data||[];clients=rc.data||[];
 $('#login-user').innerHTML='<option value="">— Selecionar —</option>'+responsaveis.map(r=>`<option value="${r.id}">${escapeHtml(r.nome)}</option>`).join('');
}
$('#login-btn').onclick=async()=>{const id=Number($('#login-user').value),pin=$('#login-pin').value.trim();const r=responsaveis.find(x=>x.id===id);if(!r||String(r.pin)!==pin){$('#login-error').textContent='Utilizador ou PIN incorreto';return}user=r;await enterApp()};
$('#login-pin').addEventListener('keydown',e=>{if(e.key==='Enter')$('#login-btn').click()});
$('#logout-btn').onclick=()=>location.reload();

async function enterApp(){
 $('#login').classList.add('hidden');$('#sidebar').classList.remove('hidden');$('#app').classList.remove('hidden');$('#session-name').textContent=user.nome;
 renderMenu();await loadYears();showPage('resumo');
}
function renderMenu(){
 $('#menu').innerHTML=groups.map(([g,items])=>`<div class="menu-group"><div class="menu-title">${g}</div>${items.filter(([id])=>id!=='auditoria'||isAdmin()).map(([id,l])=>`<button class="menu-btn" data-page="${id}">${l}</button>`).join('')}</div>`).join('');
 $$('.menu-btn').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!isAdmin()));
}
async function loadYears(){let {data,error}=await sb.from('v2_anos_fiscais').select('*').order('ano');if(error){toast('Execute primeiro o schema_v2.sql','err');return}data=data||[];$('#year-select').innerHTML=data.map(x=>`<option value="${x.ano}">${x.ano}${x.estado==='fechado'?' — fechado':''}</option>`).join('');year=Number(data.find(x=>x.estado==='aberto')?.ano||data[0]?.ano||2026);$('#year-select').value=year;$('#year-select').onchange=()=>{year=Number($('#year-select').value);showPage(currentPage)};updateYearButtons(data)}
function updateYearButtons(rows){const row=rows.find(x=>x.ano===year);$('#close-year-btn').textContent=row?.estado==='fechado'?'Reabrir ano':'Fechar ano'}
$('#open-year-btn').onclick=async()=>{const ny=Math.max(...$$('#year-select option').map(o=>Number(o.value)))+1;if(!confirm(`Abrir o ano ${ny}?`))return;const {error}=await sb.from('v2_anos_fiscais').insert({ano:ny,estado:'aberto',criado_por:user.nome});if(error)return toast(error.message,'err');await loadYears();toast(`Ano ${ny} aberto`)};
$('#close-year-btn').onclick=async()=>{const {data}=await sb.from('v2_anos_fiscais').select('*').eq('ano',year).single();const closing=data.estado!=='fechado';if(!confirm(`${closing?'Fechar':'Reabrir'} o ano ${year}?`))return;const patch=closing?{estado:'fechado',fechado_em:new Date().toISOString(),fechado_por:user.nome}:{estado:'aberto',fechado_em:null,fechado_por:null};const {error}=await sb.from('v2_anos_fiscais').update(patch).eq('ano',year);if(error)return toast(error.message,'err');await loadYears();showPage(currentPage)};
async function yearClosed(){const {data}=await sb.from('v2_anos_fiscais').select('estado').eq('ano',year).single();return data?.estado==='fechado'}

async function showPage(p){currentPage=p;$$('.menu-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#page-title').textContent=groups.flatMap(x=>x[1]).find(x=>x[0]===p)?.[1]||p;$('#content').innerHTML='<div class="empty">A carregar…</div>';
 if(p==='clientes')return renderClients();if(p==='servicos')return renderServices();if(p==='responsaveis')return renderResponsaveis();if(p==='resumo')return renderResumo();if(p==='calendario')return renderCalendar();if(p==='auditoria')return renderAudit();if(p==='iva-cessado')return renderCessados();if(moduleConfig[p])return renderModule(p);
}

function baseToolbar(extra=''){return `<div class="toolbar"><input id="search" class="grow" placeholder="Pesquisar cliente…"><select id="resp-filter"><option value="">Todos os responsáveis</option>${responsaveis.map(r=>`<option>${escapeHtml(r.nome)}</option>`).join('')}</select>${extra}</div>`}
function filteredClients(flag){const q=($('#search')?.value||'').toLowerCase(),r=$('#resp-filter')?.value||'';return clients.filter(c=>(!flag||c[flag]===true)&&c.estado==='Ativo'&&(!q||`${c.codigo} ${c.nome}`.toLowerCase().includes(q))&&(!r||c.responsavel===r))}

function renderClients(){
 $('#content').innerHTML=baseToolbar(canManage()?'<button id="new-client" class="primary">+ Novo cliente</button>':'')+`<div class="card table-wrap"><table><thead><tr><th>Cód.</th><th>Cliente</th><th>Responsável</th><th>Estado</th><th>Serviços</th></tr></thead><tbody id="client-body"></tbody></table></div>`;
 const draw=()=>{$('#client-body').innerHTML=filteredClients().map(c=>`<tr><td>${escapeHtml(c.codigo)}</td><td>${escapeHtml(c.nome)}</td><td>${escapeHtml(c.responsavel||'')}</td><td>${escapeHtml(c.estado||'')}</td><td>${Object.entries(serviceFlags).filter(([,f])=>c[f]).map(([k])=>`<span>${moduleConfig[k]?.title||k}</span>`).join(' · ')}</td></tr>`).join('')};draw();$('#search').oninput=draw;$('#resp-filter').onchange=draw;
}
function renderCessados(){
 $('#content').innerHTML=baseToolbar()+`<div class="card table-wrap"><table><thead><tr><th>Cód.</th><th>Cliente</th><th>Responsável</th><th>Data cessação</th><th>Observações</th></tr></thead><tbody id="cess-body"></tbody></table></div>`;
 const draw=()=>{const q=$('#search').value.toLowerCase(),r=$('#resp-filter').value;$('#cess-body').innerHTML=clients.filter(c=>c.iva_cessado&&(!q||`${c.codigo} ${c.nome}`.toLowerCase().includes(q))&&(!r||c.responsavel===r)).map(c=>`<tr><td>${c.codigo}</td><td>${escapeHtml(c.nome)}</td><td>${escapeHtml(c.responsavel||'')}</td><td>${fmtDate(c.data_cessacao_iva)}</td><td>${escapeHtml(c.obs_cessacao_iva||'')}</td></tr>`).join('')};draw();$('#search').oninput=draw;$('#resp-filter').onchange=draw;
}

function renderServices(){
 if(!canManage())return $('#content').innerHTML='<div class="empty">Sem permissão.</div>';
 const cols=Object.entries(serviceFlags);$('#content').innerHTML=baseToolbar(`<button id="save-services" class="primary">Guardar alterações</button><button id="reset-services" class="ghost">Repor</button>`)+`<div class="card table-wrap"><table class="matrix"><thead><tr><th>Cód.</th><th>Cliente</th><th>Responsável</th>${cols.map(([k])=>`<th><label><input type="checkbox" data-col="${k}"> ${moduleConfig[k]?.title||k}</label></th>`).join('')}</tr></thead><tbody id="svc-body"></tbody></table></div>`;
 const draw=()=>{const rows=filteredClients();$('#svc-body').innerHTML=rows.map(c=>`<tr data-id="${c.id}"><td>${c.codigo}</td><td>${escapeHtml(c.nome)}</td><td>${escapeHtml(c.responsavel||'')}</td>${cols.map(([k,f])=>`<td><input type="checkbox" data-service="${k}" ${c[f]?'checked':''}></td>`).join('')}</tr>`).join('');bindServiceEvents(rows,cols)};draw();$('#search').oninput=draw;$('#resp-filter').onchange=draw;
 $('#reset-services').onclick=()=>{dirtyServices.clear();clients.forEach(c=>delete c.__draft);draw()};$('#save-services').onclick=saveServices;
}
function bindServiceEvents(rows,cols){
 $$('[data-service]').forEach(ch=>ch.onchange=()=>{const tr=ch.closest('tr'),c=clients.find(x=>x.id===Number(tr.dataset.id)),k=ch.dataset.service,f=serviceFlags[k];c.__draft={...(c.__draft||{}),[f]:ch.checked};if(k==='iva-mensal'&&ch.checked)c.__draft.tem_iva_trimestral=false;if(k==='iva-trimestral'&&ch.checked)c.__draft.tem_iva_mensal=false;dirtyServices.set(c.id,c.__draft);tr.classList.add('dirty');if(k.startsWith('iva-')&&ch.checked){const other=tr.querySelector(`[data-service="${k==='iva-mensal'?'iva-trimestral':'iva-mensal'}"]`);if(other)other.checked=false}});
 $$('[data-col]').forEach(h=>h.onchange=()=>{const k=h.dataset.col;$$(`[data-service="${k}"]`).forEach(x=>{x.checked=h.checked;x.dispatchEvent(new Event('change'))})});
}
async function saveServices(){if(!dirtyServices.size)return toast('Sem alterações');for(const [id,patch] of dirtyServices){const {error}=await sb.from('clientes').update(patch).eq('id',id);if(error)return toast(error.message,'err');Object.assign(clients.find(c=>c.id===id),patch)}dirtyServices.clear();toast('Serviços atualizados');renderServices()}

function renderResponsaveis(){if(!isAdmin())return $('#content').innerHTML='<div class="empty">Apenas Administrador.</div>';$('#content').innerHTML=`<div class="card table-wrap"><table><thead><tr><th>Nome</th><th>Nível</th><th>Estado</th></tr></thead><tbody>${responsaveis.map(r=>`<tr><td>${escapeHtml(r.nome)}</td><td>${escapeHtml(r.nivel)}</td><td>${escapeHtml(r.estado)}</td></tr>`).join('')}</tbody></table></div>`}

async function renderModule(key){const cfg=moduleConfig[key],periodDefault=key==='iva-mensal'||key==='salarios'||key==='retencoes'||key==='modelo30'||key==='cope'?String(new Date().getMonth()+1):cfg.periods[0];$('#content').innerHTML=baseToolbar(`<select id="period-filter">${cfg.periods.map(p=>`<option value="${p}" ${p===periodDefault?'selected':''}>${p==='ano'?year:(cfg.periods.length===12?monthName(p):(p+'º Trimestre'))}</option>`).join('')}</select><span id="period-badge" class="period-badge"></span><button id="export-btn" class="ghost">Exportar Excel</button>`)+`<div class="card table-wrap"><table id="module-table"><thead><tr><th class="sticky1">Cód.</th><th class="sticky2">Cliente</th><th>Responsável</th>${cfg.fields.map(f=>`<th>${f[1]}</th>`).join('')}</tr></thead><tbody id="module-body"></tbody></table></div>`;
 const load=()=>loadModuleRows(key);$('#search').oninput=load;$('#resp-filter').onchange=load;$('#period-filter').onchange=load;$('#export-btn').onclick=exportCurrentTable;await load();}
async function loadModuleRows(key){const cfg=moduleConfig[key],period=$('#period-filter').value;$('#period-badge').textContent=period==='ano'?`ANO ${year}`:(cfg.periods.length===12?`${monthName(period).toUpperCase()} ${year}`:`${period}º TRIMESTRE ${year}`);const cls=filteredClients(cfg.flag);const ids=cls.map(c=>c.id);let tasks=[];if(ids.length){const {data,error}=await sb.from('v2_tasks').select('*').eq('modulo',key).eq('ano',year).eq('periodo',period).in('cliente_id',ids);if(error)return $('#module-body').innerHTML=`<tr><td colspan="20">${escapeHtml(error.message)}</td></tr>`;tasks=data||[]}const map=new Map(tasks.map(t=>[t.cliente_id,t]));$('#module-body').innerHTML=cls.map(c=>{const t=map.get(c.id),d=t?.dados||{};return `<tr data-client="${c.id}" data-task="${t?.id||''}"><td class="sticky1">${c.codigo}</td><td class="sticky2">${escapeHtml(c.nome)}</td><td>${escapeHtml(c.responsavel||'')}</td>${cfg.fields.map(f=>renderField(key,c,t,d,f,period)).join('')}</tr>`}).join('')||'<tr><td colspan="20" class="empty">Sem clientes.</td></tr>';bindModuleFields(key,period)}
function renderField(key,c,t,d,[field,label,type],period){let v=d[field]??'';if(type==='user'){const opts=(normRole(user.nivel)==='operacional'?[user]:responsaveis).map(r=>`<option ${v===r.nome?'selected':''}>${escapeHtml(r.nome)}</option>`).join('');return `<td><select class="cell-input" data-field="${field}" data-type="${type}"><option value=""></option>${opts}</select></td>`}if(type==='status')return `<td><select class="cell-input" data-field="${field}" data-type="${type}">${['','A lançar','Revisão','Pronto','Submetido'].map(x=>`<option ${v===x?'selected':''}>${x}</option>`).join('')}</select></td>`;if(type.startsWith('bool')){const saldo=Number(d.saldo_iva||0),allowed=type==='bool-negative'?saldo<0:saldo>0;return `<td><input type="checkbox" data-field="${field}" data-type="${type}" ${v?'checked':''} ${allowed?'':'disabled'}></td>`}const inputType=type.startsWith('date')?'date':type==='money'?'number':'text';const cls=field==='saldo_iva'?(Number(v)<0?'status-negative':Number(v)>0?'status-positive':''):'';return `<td class="${cls}"><input class="cell-input" data-field="${field}" data-type="${type}" type="${inputType}" step="0.01" value="${escapeHtml(v)}"></td>`}
function bindModuleFields(key,period){$$('#module-body [data-field]').forEach(el=>el.onchange=async()=>{if(await yearClosed())return toast('Ano fechado: apenas consulta.','err');const tr=el.closest('tr'),cid=Number(tr.dataset.client),field=el.dataset.field,type=el.dataset.type;let nv=type.startsWith('bool')?el.checked:el.value;if(type==='money')nv=nv===''?null:Number(nv);if(normRole(user.nivel)==='operacional'&&field==='resp_execucao')nv=user.nome;await saveTaskField(key,cid,period,field,nv);if(field==='saldo_iva')await loadModuleRows(key)});}
async function saveTaskField(modulo,cliente_id,periodo,campo,valor){let {data:existing,error:e1}=await sb.from('v2_tasks').select('*').eq('modulo',modulo).eq('cliente_id',cliente_id).eq('ano',year).eq('periodo',periodo).maybeSingle();if(e1)return toast(e1.message,'err');const old=existing?.dados?.[campo]??null,dados={...(existing?.dados||{}),[campo]:valor};const payload={modulo,cliente_id,ano:year,periodo,dados,updated_by:user.nome};let q=existing?sb.from('v2_tasks').update(payload).eq('id',existing.id).select().single():sb.from('v2_tasks').insert(payload).select().single();const {data,error}=await q;if(error)return toast(error.message,'err');const {error:ae}=await sb.from('v2_audit_logs').insert({task_id:data.id,modulo,cliente_id,ano:year,periodo,campo,valor_anterior:old,valor_novo:valor,utilizador:user.nome});if(ae)toast('Guardado, mas auditoria falhou: '+ae.message,'err');else toast('Guardado')}
function exportCurrentTable(){const table=$('#module-table');let html='<table>'+table.innerHTML+'</table>';html=html.replace(/<input[^>]*value="([^"]*)"[^>]*>/g,'$1').replace(/<select[^>]*>[\s\S]*?<\/select>/g,'');const blob=new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${currentPage}_${year}.xls`;a.click();URL.revokeObjectURL(a.href)}

async function renderResumo(){const {data:tasks,error}=await sb.from('v2_tasks').select('*').eq('ano',year);if(error)return $('#content').innerHTML='<div class="empty">'+escapeHtml(error.message)+'</div>';const all=tasks||[],pending=all.filter(t=>['','A lançar','Revisão'].includes(t.dados.estado||'')).length,submitted=all.filter(t=>t.dados.estado==='Submetido').length,ivaNoBanks=all.filter(t=>['iva-mensal','iva-trimestral'].includes(t.modulo)&&t.dados.lancamento&&!(t.dados.bancos||t.dados.bancos_m1||t.dados.bancos_m2||t.dados.bancos_m3)).length;$('#content').innerHTML=`<div class="kpis"><div class="kpi"><strong>${pending}</strong><span>Tarefas pendentes</span></div><div class="kpi"><strong>${submitted}</strong><span>Submetidas</span></div><div class="kpi"><strong>${ivaNoBanks}</strong><span>IVA lançado sem bancos</span></div></div><div class="card"><div class="empty">Resumo V2 baseado numa única fonte de dados, sem consultas concorrentes.</div></div>`}

async function renderAudit(){if(!isAdmin())return $('#content').innerHTML='<div class="empty">Apenas Administrador.</div>';const {data,error}=await sb.from('v2_audit_logs').select('*').order('criado_em',{ascending:false}).limit(500);if(error)return $('#content').innerHTML='<div class="empty">'+escapeHtml(error.message)+'</div>';const cmap=new Map(clients.map(c=>[c.id,c]));$('#content').innerHTML=`<div class="card table-wrap"><table><thead><tr><th>Data</th><th>Utilizador</th><th>Módulo</th><th>Cliente</th><th>Período</th><th>Campo</th><th>Anterior</th><th>Novo</th></tr></thead><tbody>${(data||[]).map(a=>`<tr><td>${new Date(a.criado_em).toLocaleString('pt-PT')}</td><td>${escapeHtml(a.utilizador||'')}</td><td>${escapeHtml(a.modulo)}</td><td>${escapeHtml(cmap.get(a.cliente_id)?.nome||'')}</td><td>${a.ano} / ${escapeHtml(a.periodo||'')}</td><td>${escapeHtml(a.campo||'')}</td><td>${escapeHtml(JSON.stringify(a.valor_anterior))}</td><td>${escapeHtml(JSON.stringify(a.valor_novo))}</td></tr>`).join('')}</tbody></table></div>`}

async function renderCalendar(){const now=new Date(),m=now.getMonth(),y=year;const {data,error}=await sb.from('v2_calendario_fiscal').select('*').eq('ano',y).order('data_limite');if(error)return $('#content').innerHTML='<div class="empty">'+escapeHtml(error.message)+'</div>';const events=data||[];$('#content').innerHTML=`<div class="toolbar"><button id="prev-month" class="ghost">‹</button><span id="cal-title" class="period-badge"></span><button id="next-month" class="ghost">›</button><button id="today-month" class="ghost">Hoje</button></div><div id="calendar"></div>`;let cm=m;const draw=()=>drawCalendar(y,cm,events);$('#prev-month').onclick=()=>{cm=(cm+11)%12;draw()};$('#next-month').onclick=()=>{cm=(cm+1)%12;draw()};$('#today-month').onclick=()=>{cm=new Date().getMonth();draw()};draw()}
function drawCalendar(y,m,events){$('#cal-title').textContent=`${monthName(m+1).toUpperCase()} ${y}`;const first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate();let cells=[];for(let i=0;i<42;i++){let d=i-start+1,other=false,cm=m,cy=y;if(d<1){d=prevDays+d;cm=m-1;other=true}else if(d>days){d-=days;cm=m+1;other=true}const iso=`${cy}-${String(cm+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ev=events.filter(e=>e.data_limite===iso);cells.push(`<div class="day ${other?'other':''} ${iso===new Date().toISOString().slice(0,10)?'today':''}"><strong>${d}</strong>${ev.map(e=>`<button class="event ${e.tipo==='Pagamento'?'pay':''}">${escapeHtml(e.obrigacao)}</button>`).join('')}</div>`)}$('#calendar').innerHTML=`<div class="month-grid">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<div class="weekday">${x}</div>`).join('')}${cells.join('')}</div>`}

boot();
